name: Run tests

on:
  push:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master

      #- name: run shunit2 tests
      #  uses: TheColvinCo/shunit2-github-action@v1.2
      #  env:
      #    SHUNIT_TEST_FOLDER: "test"
